package com.accordserver.controller;

import com.accordserver.ResponseMessage;
import com.accordserver.accessingdatamysql.categories.Categories;
import com.accordserver.accessingdatamysql.categories.CategoriesRepository;
import com.accordserver.accessingdatamysql.channels.Channels;
import com.accordserver.accessingdatamysql.channels.ChannelsRepository;
import com.accordserver.accessingdatamysql.server.Server;
import com.accordserver.accessingdatamysql.server.ServerRepository;
import com.accordserver.accessingdatamysql.user.User;
import com.accordserver.accessingdatamysql.user.UserRepository;
import com.accordserver.webSocket.SystemWebSocketHandler;
import com.github.cliftonlabs.json_simple.JsonArray;
import com.github.cliftonlabs.json_simple.JsonObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

import static com.accordserver.util.Constants.*;

@RestController
public class ServerController {

    // This means to get the bean called serverRepository,... . Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private ServerRepository serverRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private CategoriesRepository categoriesRepository;

    @Autowired
    private ChannelsRepository channelsRepository;

    @Autowired
    private SystemWebSocketHandler systemWebSocketHandler;

    /**
     * creates a new server
     * AND needs to control the ManyToMany connection with User.
     *
     * @param data    name of the new Server
     * @param userKey key of the currentUser
     * @return rest answer
     */
    @PostMapping("/servers") // Map ONLY POST Requests - createServer
    public @ResponseBody
    ResponseMessage createServer(@RequestBody Map<String, Object> data, @RequestHeader(value = USER_KEY) String userKey) {
        User currentUser = userRepository.findByUserKey(userKey);

        // here it is important to set the one class to the many class
        Server newServer = new Server(data.get("name").toString()).setOwner(currentUser.getId());
        Categories newCategory = new Categories("default-category", newServer);
        Channels newChannel = new Channels("default-text-channel", "text", false, newCategory, newServer);

        // save newChannel to newCategory (ONLY FOR USE THE OBJECTS IN THIS METHOD, NO IMPACT TO mySQL!)
        newCategory.setChannel(newChannel);

        // save newCategory & newChannel to newServer (ONLY FOR USE THE OBJECTS IN THIS METHOD, NO IMPACT TO mySQL!)
        newServer.setCategory(newCategory).setChannel(newChannel);

        // set currentUser to the first Member
        newServer.setMembers(currentUser);
        currentUser.setMemberServers(newServer);

        serverRepository.save(newServer);
        categoriesRepository.save(newCategory);
        channelsRepository.save(newChannel);

        currentUser.setServer(newServer);
        userRepository.save(currentUser);

        JsonObject serverData = new JsonObject();
        serverData.put("id", newServer.getId());
        serverData.put("name", newServer.getName());

        return new ResponseMessage(SUCCESS, "", serverData);
    }

    /**
     * Gets all serversInfo
     * WHO CAN DO? -> ALL SERVER USER
     *
     * @param userKey  key of the user
     * @param serverId id of the current server
     * @return json list of all server
     */
    @GetMapping("/servers/{id}")
    public @ResponseBody
    ResponseMessage getServersInfo(@RequestHeader(value = USER_KEY) String userKey, @PathVariable("id") String serverId) {
        User currentUser = userRepository.findByUserKey(userKey);

        Server currentServer = serverRepository.findById(serverId).get();

        JsonObject responseServerData = new JsonObject();
        responseServerData.put("id", currentServer.getId());
        responseServerData.put("name", currentServer.getName());
        responseServerData.put("owner", currentServer.getOwner());
        responseServerData.put("categories", new JsonArray().addAll(currentServer.getCategories()));

        JsonArray jsonArray = new JsonArray();
        for (User user : currentServer.getMembers()) {
            JsonObject jsonObject = new JsonObject();
            jsonObject.put("id", user.getId());
            jsonObject.put("name", user.getName());
            jsonObject.put("online", user.isOnline());
            jsonObject.put("description", user.getDescription());
            jsonArray.add(jsonObject);
        }
        responseServerData.put("members", jsonArray);

        return new ResponseMessage(SUCCESS, "", responseServerData);
    }

    /**
     * Get all servers
     * WHO CAN DO? -> ALL SERVER USER
     *
     * @param userKey key of the user
     * @return json list of all server
     */
    @GetMapping("/servers")
    public @ResponseBody
    ResponseMessage getServers(@RequestHeader(value = USER_KEY) String userKey) {
        User currentUser = userRepository.findByUserKey(userKey);

        List<Server> serverList = (List<Server>) serverRepository.findByOwner(currentUser.getId());

        JsonArray responseServerDataList = new JsonArray();
        for (Server server : serverList) {
            JsonObject responseServerData = new JsonObject();
            responseServerData.put("id", server.getId());
            responseServerData.put("name", server.getName());

            responseServerDataList.add(responseServerData);
        }

        return new ResponseMessage(SUCCESS, "", responseServerDataList);
    }

    /**
     * Change server name
     * WHO CAN DO? -> ONLY OWNER
     *
     * @param userKey key of the user
     * @return json list of all server
     */
    @PutMapping("/servers/{id}")
    public @ResponseBody
    ResponseMessage updateServer(@RequestBody Map<String, Object> data, @RequestHeader(value = USER_KEY) String userKey, @PathVariable("id") String serverId) {
        User currentUser = userRepository.findByUserKey(userKey);

        String newServerName = data.get("name").toString();

        Server currentServer = serverRepository.findById(serverId).get();

        if (currentServer.getOwner().equals(currentUser.getId())) {

            // update server
            currentServer.setName(newServerName);
            serverRepository.save(currentServer);

            // send webSocket message
            systemWebSocketHandler.sendServerUpdated(currentServer);

            // return json
            JsonObject serverData = new JsonObject();
            serverData.put("id", currentServer.getId());
            serverData.put("name", currentServer.getName());

            return new ResponseMessage(SUCCESS, "", serverData);
        } else {
            return new ResponseMessage(FAILED, "This is not your server!", new JsonObject());
        }
    }
}